# nopycln: file
from starlette.status import *  # type: ignore

try:
    HTTP_422_UNPROCESSABLE_ENTITY
except NameError:
    HTTP_422_UNPROCESSABLE_CONTENT
    HTTP_422_UNPROCESSABLE_ENTITY = HTTP_422_UNPROCESSABLE_CONTENT


UNDEFINED_ERROR_CODE = 520
