# nopycln: file
from starlette.status import *  # type: ignore

try:
    HTTP_422_UNPROCESSABLE_ENTITY
except NameError:
    HTTP_422_UNPROCESSABLE_ENTITY = HTTP_422_UNPROCESSABLE_CONTENT


UNDEFINED_ERROR_CODE = 520
JWT_TOKEN_SIGNATURE_EXPIRED = 530
JWT_TOKEN_SIGNATURE_INVALID = 531
JWT_TOKEN_MISSING = 532
